steps:
# build & push with jib:
#   mvn compile jib:build
  # - id: jib-compile-push
  #   name: "gcr.io/cloud-builders/mvn"
  #   args:
  #   - compile
  #   - -X
  #   - com.google.cloud.tools:jib-maven-plugin:build

# deploy revision to Cloud Run
#   gcloud run deploy --quiet pdf-merger-2 --region=europe-west1 --platform=managed --no-traffic --image gcr.io/alexismp-pdfmerger/pdfmerger:latest
  - id: cloudrun-revision-deploy
    name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "--quiet",
        "pdf-merger-2",
        "--region=europe-west1",
        "--platform=managed",
        # "--no-traffic",
        "--image=gcr.io/alexismp-pdfmerger/pdfmerger:latest"
      ]